### ISSUE TITLE
The implementation problems of flame and badnet

### ISSUE THREAD

**Issue by andyclsr** [zhmzm/FLAME#3] opened 2023-04-18 02:26 UTC
Hi, I encountered some problems when I checked your code and I had no idea whether it was just my misunderstanding.
In MaliciousUpdate, this simple concatenation of bad data and benign data will cause bad learning of trigger since it will lead the model to learn the sequential information. Randomization would be better.
https://github.com/zhmzm/FLAME/blob/1c354ab458529cb1eeb300967a42cac5b787ff1b/models/MaliciousUpdate.py#L149-L152
second is flame's problem:
https://github.com/zhmzm/FLAME/blob/1c354ab458529cb1eeb300967a42cac5b787ff1b/utils/defense.py#L311-L325
in the paper, norm_list is calculated using all the local models.

**Comment by zhmzm** [comment] 2023-04-18 13:50
Yes, you are right. The median is calculated in all uploaded models. The problem is fixed now.
https://github.com/zhmzm/FLAME/blob/f54eb25ec4e56e1bac3fda79c25a8a3fa408b5c8/utils/defense.py#L323-L325
I believe that this simple concatenation of poisoned data and clean data in the same batch helps to learn the trigger (from my observation). When args.poison_frac is set to less than 1, randomization is included in the poisoned dataset. 
https://github.com/zhmzm/FLAME/blob/1c354ab458529cb1eeb300967a42cac5b787ff1b/models/MaliciousUpdate.py#L153-L165
By the way, Do you know which papers mention that such concatenation harms the learning of the backdoor attacks?

**Comment by andyclsr** [comment] 2023-04-19 15:48
Sorry to reply late and I think it is my wrong memory for the things about concatenation. I can't remember the details of my experiment result of your code and what I did remember is that I found sometimes even without defense the fedavg can bypass the attack with really low asr. For this, I can't guarantee the description above is exact since I may make some changes to your code by chance and I probably didn't notice it. But the result is that I change your maliciousupdate.py. 

I will check this when I am available.
thanks, wish you a great day.

**Closed as completed** 2023-04-20 13:17 UTC
